'use client';
import { PrimAppIcon } from '@/components/PrimLogo';

/**
 * Presentational report sheet — renders a view-model from lib/reports.mjs.
 * Always white-background so the on-screen view is identical to the PDF.
 * The outer .report-sheet class is what the print stylesheet isolates.
 *
 * Props:
 *   report   — a built report view-model (table or summary layout)
 *   period   — { label } resolved period
 *   agentName — string shown in the header band
 */
export default function ReportSheet({ report, period, agentName }) {
  if (!report) return null;
  const generated = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
  });

  return (
    <div
      className="report-sheet bg-white text-slate-900 rounded-xl border border-slate-200 shadow-sm mx-auto"
      style={{ maxWidth: 900, width: '100%' }}
    >
      {/* Header band — report identity color */}
      <div
        className="flex items-center justify-between px-6 py-4 rounded-t-xl"
        style={{ background: report.identityColor }}
      >
        <div className="flex items-center gap-2 text-white">
          <PrimAppIcon size={34} />
          <div>
            <div className="font-extrabold text-lg leading-none">PRIM</div>
            <div className="text-[10px] opacity-90 tracking-wide">
              Performance · Revenue · Investment
            </div>
          </div>
        </div>
        <div className="text-right text-white">
          <div className="font-bold text-lg leading-tight">{report.title} Report</div>
          <div className="text-xs opacity-90">{period?.label}</div>
          <div className="text-[10px] opacity-80">
            {agentName ? `${agentName} · ` : ''}Generated {generated}
          </div>
        </div>
      </div>

      <div className="p-6">
        {/* KPI strip */}
        {report.kpis?.length > 0 && (
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-6">
            {report.kpis.map((k, i) => (
              <div key={i} className="border border-slate-200 rounded-lg p-3">
                <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">
                  {k.label}
                </div>
                <div className="text-lg font-extrabold mt-1" style={{ color: k.color }}>
                  {k.value}
                </div>
              </div>
            ))}
          </div>
        )}

        {report.empty ? (
          <div
            className="text-center py-10 text-sm font-medium"
            style={{ color: report.identityColor }}
          >
            {report.emptyMessage}
          </div>
        ) : report.layout === 'summary' ? (
          <SummaryBody report={report} />
        ) : (
          <TableBody report={report} />
        )}
      </div>

      {/* Footer */}
      <div className="px-6 py-3 border-t border-slate-200 flex justify-between text-[10px] text-slate-400">
        <span>Generated by PRIM · primtracker.com</span>
        <span>{period?.label}</span>
      </div>
    </div>
  );
}

function TableBody({ report }) {
  return (
    <table className="w-full text-sm border-collapse">
      <thead>
        <tr className="border-b-2 border-slate-200">
          {report.columns.map((c, i) => (
            <th
              key={i}
              className={`py-2 px-2 text-[10px] font-bold uppercase tracking-wider text-slate-500 ${
                c.align === 'right' ? 'text-right' : 'text-left'
              }`}
            >
              {c.label}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {report.rows.map((row, ri) => (
          <tr key={ri} className={ri % 2 ? 'bg-slate-50' : ''}>
            {row.map((cell, ci) => (
              <td
                key={ci}
                className={`py-1.5 px-2 ${cell.align === 'right' ? 'text-right tabular-nums' : 'text-left'}`}
                style={{ color: cell.color }}
              >
                {cell.text}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
      {report.totalsRow && (
        <tfoot>
          <tr className="border-t-2 border-slate-300 font-bold">
            {report.totalsRow.map((cell, ci) => (
              <td
                key={ci}
                className={`py-2 px-2 ${cell.align === 'right' ? 'text-right tabular-nums' : 'text-left'}`}
                style={{ color: cell.color }}
              >
                {cell.text}
              </td>
            ))}
          </tr>
        </tfoot>
      )}
    </table>
  );
}

function SummaryBody({ report }) {
  return (
    <div className="max-w-lg mx-auto">
      {report.sections.map((sec, si) => (
        <div key={si} className="mb-5">
          <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">
            {sec.title}
          </div>
          {sec.lines.map((ln, li) => (
            <div key={li} className="flex justify-between py-1 text-sm">
              <span className="text-slate-700">{ln.label}</span>
              <span className="font-semibold tabular-nums" style={{ color: ln.color }}>
                {ln.amount}
              </span>
            </div>
          ))}
          <div className="flex justify-between py-1.5 mt-1 border-t border-slate-200 text-sm font-bold">
            <span>{sec.subtotal.label}</span>
            <span className="tabular-nums" style={{ color: sec.subtotal.color }}>
              {sec.subtotal.amount}
            </span>
          </div>
        </div>
      ))}
      <div
        className="flex justify-between items-center px-4 py-4 rounded-lg mt-4"
        style={{ background: `${report.net.color}14` }}
      >
        <span className="font-bold text-slate-900">{report.net.label}</span>
        <span className="text-3xl font-extrabold tabular-nums" style={{ color: report.net.color }}>
          {report.net.amount}
        </span>
      </div>
    </div>
  );
}
