'use client';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border border-slate-200 p-8 md:p-12">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-indigo-600 hover:text-indigo-700 mb-8">
          <ArrowLeft size={14} /> Back to PRIM
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-8">Last updated: April 28, 2026</p>

        <div className="prose prose-slate max-w-none space-y-6 text-slate-700">
          <p className="text-amber-800 bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm">
            <strong>Placeholder.</strong> A finalized Terms of Service generated by Termly or Iubenda will replace this before public launch. The plain-English summary below governs current use.
          </p>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">1. Plain summary</h2>
            <p>PRIM (&quot;the app&quot;) is a CPA / pipeline / books tracker for insurance agents. Use it for your own business. Don&apos;t break it on purpose. We don&apos;t guarantee uptime or that the math is correct for your tax filing — verify your own numbers.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">2. NO PHI / no clinical data</h2>
            <p className="bg-red-50 border border-red-200 rounded-lg p-3"><strong>This is important.</strong> The app is NOT a HIPAA-compliant platform. You agree NOT to enter Protected Health Information into any field, including but not limited to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Specific medication names (e.g. &quot;Metformin&quot;)</li>
              <li>Specific diagnoses (e.g. &quot;Type 2 Diabetes&quot;)</li>
              <li>Lab results, doctor names, treatment details</li>
            </ul>
            <p>For prospect notes, use general impressions only — e.g. &quot;Has health concerns&quot; or &quot;Wants better coverage,&quot; not clinical specifics. You are solely responsible for compliance with HIPAA and applicable health-information laws on the data you enter.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">3. Your account</h2>
            <p>Keep your password secret. You&apos;re responsible for everything done from your account. If you suspect compromise, email us right away.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">4. Your data is yours</h2>
            <p>You own everything you put into the app. We get a limited license to store and process it so the service works. We don&apos;t sell it.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">5. Disclaimer & limitation of liability</h2>
            <p>The app is provided &quot;as is.&quot; We&apos;re not responsible for tax, legal, or financial decisions you make based on what the app shows. Math errors happen — verify the numbers. To the maximum extent allowed by law, our liability for any claim is limited to fees paid in the prior 12 months (or $50 if no fees were paid).</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">6. Acceptable use</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Don&apos;t try to break, hack, or reverse-engineer the app</li>
              <li>Don&apos;t upload illegal content, malware, or someone else&apos;s data without permission</li>
              <li>Don&apos;t resell access to your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">7. Termination</h2>
            <p>You can close your account anytime by emailing us. We can suspend accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">8. Contact</h2>
            <p>Juan Trejo · <a href="mailto:juantrejo9082@gmail.com" className="text-indigo-600 hover:underline">juantrejo9082@gmail.com</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
