'use client';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border border-slate-200 p-8 md:p-12">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-indigo-600 hover:text-indigo-700 mb-8">
          <ArrowLeft size={14} /> Back to PRIM
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-slate-500 mb-1">Last updated: April 28, 2026</p>
        <p className="text-sm text-slate-500 mb-8">PRIM is operated by R&amp;J Prime Consultancy LLC, a Florida limited liability company.</p>

        <div className="prose prose-slate max-w-none space-y-6 text-slate-700">
          <p className="text-amber-800 bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm">
            <strong>Placeholder.</strong> A finalized Privacy Policy generated by a service like Termly or Iubenda will replace this content before public launch. The summary below describes our current data practices in plain language.
          </p>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">What we collect</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Account info: your email and a hashed password (handled by Supabase Auth).</li>
              <li>App data you enter: leads, prospects, expenses, income, statement uploads, attachments.</li>
              <li>Basic usage logs (page views, errors) for debugging.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">What we do NOT collect</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>We do not sell or share your data with third parties for marketing.</li>
              <li>We do not collect Protected Health Information (PHI). You are responsible for not entering medication names, diagnoses, or other clinical data into the app — see the Terms of Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">Where it lives</h2>
            <p>Your data is stored on Supabase (PostgreSQL + storage), hosted on AWS in the US. Each account&apos;s data is isolated via row-level security — other users cannot see yours.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">Your rights</h2>
            <p>Email <a href="mailto:rjprimeconsult@gmail.com" className="text-indigo-600 hover:underline">rjprimeconsult@gmail.com</a> to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Export all your data</li>
              <li>Delete your account and all associated data</li>
              <li>Correct or update any information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">Cookies</h2>
            <p>We use a single auth cookie (Supabase) to keep you signed in. No tracking pixels, no third-party advertising cookies.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mt-6 mb-3">Contact</h2>
            <p>R&amp;J Prime Consultancy LLC<br/>
            Attn: Juan Trejo<br/>
            <a href="mailto:rjprimeconsult@gmail.com" className="text-indigo-600 hover:underline">rjprimeconsult@gmail.com</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
